language: node_js
node_js:
  - "4"

install:
  - npm install
  - npm install pixi-gl-core -save
  - npm install bit-twiddle

cache:
  directories:
    - node_modules

before_script:
  - npm install -g gulp

script:
  - gulp
  - gulp test
