language: node_js
node_js:
  - "4"

install:
  - npm install
  - npm install pixi-gl-core -save
  - npm install bit-twiddle
  - npm install gulp-babel

cache:
  directories:
    - node_modules

script:
  - gulp build
